### ISSUE TITLE
Model Manager respects .../ComfyUI/extra_model_paths.yaml

### ISSUE THREAD

**Issue by peddyhh** [Comfy-Org/ComfyUI-Manager#1391]
Kind of feature request: **Model Manager respects .../ComfyUI/extra_model_paths.yaml**

Because of space on my SSD, I have to move a lot of models on external SSD.
So i use `../ComfyUI/extra_model_paths.yaml` with Entries like that:

```
comfyui:
     base_path: /Users/comfyuser/git/zz_privat/ComfyUI/
     checkpoints: /Volumes/SD/checkpoints
     ....
     embeddings: /Volumes/SD/embeddings/
     ....
     ultralytics: /Volumes/SD//SD/ultralytics/
```

When I want to check, which "comfy official" models are installed or searching for a special model, comfyui-manager does not show the already installed models:
![grafik](https://github.com/user-attachments/assets/7cd1f1fc-d57e-4cbd-a4d3-2f3079c6134e)

The Models are installed and useable:
```
find SD/(embeddings|ultralytics) -iname "*deep*"
SD/embeddings/SD1.5/ng_deepnegative_v1_75t.pt
SD/ultralytics/bbox/deepfashion2_yolov8s-seg.pt
SD/ultralytics/segm/deepfashion2_yolov8s-seg.pt
```

Please let me know, when I missed something. I'm new to ComfyUI and ComfyUI-Manager, so I'm not sure, working with extra_model_paths.yaml is the right way to do.

Everything is updated:
![grafik](https://github.com/user-attachments/assets/b2060ac5-318b-4b13-ace2-bed0e8bacd7c)
