### ISSUE TITLE
Model Install Path

### ISSUE THREAD

**Issue by choseokheeee** [Comfy-Org/ComfyUI-Manager#688]
I set the model path to a custom path by changing the extra_model_paths.yaml
```
comfyui:
     base_path: /custom/path/
     checkpoints: models/checkpoints/
     clip: models/clip/
     clip_vision: models/clip_vision/
     configs: models/configs/
     controlnet: models/controlnet/
     embeddings: models/embeddings/
     loras: models/loras/
     upscale_models: models/upscale_models/
     vae: models/vae/
```
     
But when I install models using the Manager, the model is installed in the ComfyUI folder(where the main.py file exists), not the custom path i set

This still works(?), but I want to change the default installation path to a custom path

**Comment by liusida** [comment]
This is expected, @choseokheeee .

ComfyUI defines the main model folder to be `./models/`, and can load extra models from `extra_model_paths`.

I'm not sure if it is appropriate for Manager to download models to a custom folder instead of to the main model folder.

**Comment by Amit30swgoh** [comment]
> I set the model path to a custom path by changing the extra_model_paths.yaml
> 
> ```
> comfyui:
>      base_path: /custom/path/
>      checkpoints: models/checkpoints/
>      clip: models/clip/
>      clip_vision: models/clip_vision/
>      configs: models/configs/
>      controlnet: models/controlnet/
>      embeddings: models/embeddings/
>      loras: models/loras/
>      upscale_models: models/upscale_models/
>      vae: models/vae/
> ```
> 
> But when I install models using the Manager, the model is installed in the ComfyUI folder(where the main.py file exists), not the custom path i set
> 
> This still works(?), but I want to change the default installation path to a custom path

1. Find the extra-model-paths.yaml File:

This file is typically located in the same directory as your main.py file (the main ComfyUI script).
2. Modify the base_path:

Open the extra-model-paths.yaml file in a text editor.

Change the base_path entry to your desired custom path:

YAML
comfyui:
    base_path: /your/custom/path/
    # ... (rest of the file)
Use code [with caution.](https://github.com/faq#coding)
content_copy
3. Restart ComfyUI:

Close ComfyUI if it's running.
Restart it, and hopefully, ComfyUI-Manager will now install models in your custom path!
Why This Might Work:

Some versions of ComfyUI-Manager might check the base_path in extra-model-paths.yaml to determine the installation location. However, this behavior is not officially documented and might not work in all cases.

Important Note:

If this doesn't work, the environment variable method (COMFYUI_MODELS_PATH) or the configuration file method (if available) are more reliable ways to change the installation path.

**Comment by liusida** [comment]
> I set the model path to a custom path by changing the extra_model_paths.yaml
> 
> ```
> comfyui:
>      base_path: /custom/path/
>      checkpoints: models/checkpoints/
>      clip: models/clip/
>      clip_vision: models/clip_vision/
>      configs: models/configs/
>      controlnet: models/controlnet/
>      embeddings: models/embeddings/
>      loras: models/loras/
>      upscale_models: models/upscale_models/
>      vae: models/vae/
> ```
> 
> But when I install models using the Manager, the model is installed in the ComfyUI folder(where the main.py file exists), not the custom path i set
> 
> This still works(?), but I want to change the default installation path to a custom path

another workaround is to use `docker`, which can mount your directory as `/ComfyUI/models` to replace the old one. 
or on Linux, delete the `/ComfyUI/models` and make a symbol link using `ln -s <your folder> <models in Comfy>`.

**Comment by liusida** [comment]
> > I set the model path to a custom path by changing the extra_model_paths.yaml
> > ```
> > comfyui:
> >      base_path: /custom/path/
> >      checkpoints: models/checkpoints/
> >      clip: models/clip/
> >      clip_vision: models/clip_vision/
> >      configs: models/configs/
> >      controlnet: models/controlnet/
> >      embeddings: models/embeddings/
> >      loras: models/loras/
> >      upscale_models: models/upscale_models/
> >      vae: models/vae/
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But when I install models using the Manager, the model is installed in the ComfyUI folder(where the main.py file exists), not the custom path i set
> > This still works(?), but I want to change the default installation path to a custom path
> 
> 1. Find the extra-model-paths.yaml File:
> 
> This file is typically located in the same directory as your main.py file (the main ComfyUI script). 2. Modify the base_path:
> 
> Open the extra-model-paths.yaml file in a text editor.
> 
> Change the base_path entry to your desired custom path:
> 
> YAML comfyui: base_path: /your/custom/path/ # ... (rest of the file) Use code [with caution.](https://github.com/faq#coding) content_copy 3. Restart ComfyUI:
> 
> Close ComfyUI if it's running. Restart it, and hopefully, ComfyUI-Manager will now install models in your custom path! Why This Might Work:
> 
> Some versions of ComfyUI-Manager might check the base_path in extra-model-paths.yaml to determine the installation location. However, this behavior is not officially documented and might not work in all cases.
> 
> Important Note:
> 
> If this doesn't work, the environment variable method (COMFYUI_MODELS_PATH) or the configuration file method (if available) are more reliable ways to change the installation path.

Is this produced by some LLMs? I feel like there's hallucination all over the place.

**Comment by simonknittel** [comment]
I think it would be great if you could choose for each download between the local folder and the custom one (extra_model_paths).

**Comment by ltdrdata** [comment]
I'll handle this after CNR update is completed.

**Comment by devwearsprada** [comment]
any update on this?

**Comment by ltdrdata** [comment]
This feature will be implemented on new branch.

**Comment by executorrr86** [comment]
any update ?

**Comment by ltdrdata** [comment]
> any update ?

This is updated already.

You can use like this.
```
    some_extra_path:
       base_path: /path/to/base
       download_model_base: models
       checkpoints: models/checkpoints
       text_encoders: models/text_encoders
       vae: models/vae
       loras: models/loras
       controlnet: models/controlnet
       clip_vision: models/clip_vision
       gligen: models/gligen
       upscale_models: models/upscale_models
       embeddings: models/embeddings
       diffusion_models: models/diffusion_models
       custom_nodes: custom_nodes
       is_default: True
```

`download_model_base` is important.
