### ISSUE TITLE
Missing Models and Custom Nodes in ComfyUI, including IP-Adapters (I would like to contribute and try fix this)

### ISSUE THREAD

**Issue by MiladZarour** [Comfy-Org/ComfyUI-Manager#719]
When using ComfyUI and running run_with_gpu.bat, importing a JSON file may result in missing nodes. This issue can be easily fixed by opening the manager and clicking on "Install Missing Nodes," allowing us to check and install the required nodes.

However, this functionality does not extend to missing models or IP-adapters.

To address this, I suggest implementing a feature that allows the installation of missing models and other components directly from the manager tab when importing a JSON file. This would streamline the process and ensure all necessary components are installed seamlessly.

I would like to contribute and try fixing this issue.

**Comment by MiladZarour** [comment]
I am wondering when we press on Install Models, where the information is fetched from ? 
I mean are we fetching the models from www.kaggle.com , or www.civitai.com www.huggingface.co ?

**Comment by MiladZarour** [comment]
something like this

![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/50852900/7e2ed0f6-7a95-4f1e-a51c-94adf991443d)

**Comment by MiladZarour** [comment]
I implement a code that show the missing Models (as the first step)
but the thing is this may never works due to that "comfyui" by it's self directly take some default models (if they are installed in checkpoints...etc)
not sure where to find this functionality in confyui and disable it for this case , I may check that first in comfyui and try to get the missing models without loading the default models

here is the code so far if anyone would like to try : 

in comfui-manager.js 
add this code in line 726 or 725

```
$el("button.cm-button", {
					type: "button",
					textContent: "Install Missing Models",
					onclick:
						() => {
							if(!ModelInstaller.instance)
								ModelInstaller.instance = new ModelInstaller(app, self);
							ModelInstaller.instance.show();
						}
				}),
```

in model-downloader.js : 

in class ModelInstaller extends ComfyDialog, added this : 

```

	static ShowMode = {
		NORMAL: 0,
		MISSING_NODES: 1,
		UPDATE: 2,
	};
```
and in the end of the code , added this function : 
```
	async showMissingModels() {
		try {
			this.clear();
			const allModels = (await getModelList()).models;
			const missingModels = allModels.filter(model => model.installed !== 'True');
			this.data = { models: missingModels };

			while (this.element.children.length) {
				this.element.removeChild(this.element.children[0]);
			}

			await this.createHeaderControls();

			if(this.search_keyword) {
				this.search_box.value = this.search_keyword;
			}

			await this.createGrid();
			await this.createBottomControls();

			this.apply_searchbox(this.data);
			this.element.style.display = "block";
			this.element.style.zIndex = 10001;
		}
		catch(exception) {
			app.ui.dialog.show(`Failed to get missing model list. / ${exception}`);
		}
	}


```

after that we can start developing the functionality for ipadapters

**Comment by ltdrdata** [comment]
If you would like to contribute, please make a PR.

And for information about the models, please check the `model-list.json`.

https://github.com/ltdrdata/ComfyUI-Manager/blob/a040ed45575be06cc2f4c0dc420d7f900e8bd8cd/glob/manager_server.py#L560

**Comment by MiladZarour** [comment]
Thanks @ltdrdata
I will check that
But can I make Pull request already now?
I know the code now is not working as it should be , I am still figuring out how it can be done

**Comment by ltdrdata** [comment]
> Thanks @ltdrdata I will check that But can I make Pull request already now? I know the code now is not working as it should be , I am still figuring out how it can be done

Of course, do it when you are ready.

**Comment by liusida** [comment]
Downloading missing models is a painful job.

- Some custom nodes have Python code that downloads models the first time they are loaded onto the system, which can confuse users about why ComfyUI takes so long to restart. This is especially true when a firewall blocks the downloading process.
- Some nodes simply list the models in their repo's README.md, requiring users to download them manually (for example, IPAdapter Plus). 
- Others are more user-friendly, only starting to download necessary models the first time you run their `Load` node, but some forget to honor the proxy environment variable and try to connect to unreachable sites (for example, WD14 Tagger).

On the other hand, I really like the installation process of a node: the Manager just clones the folder and runs `pip install` for the requirements. Clean and nice.

I was thinking, is it possible to come up with a file format like `required_models.json` (filename to be discussed), and encourage new nodes to produce this file in their project directory, so the Manager can download the files for the users? Because of the popularity of the Manager, I think it is possible to set this standard, and the authors of nodes will follow it since they don't need to write downloading code anymore.

Is it a valid idea? @ltdrdata

**Comment by liusida** [comment]
As a proof-of-concept, ChatGPT just gives me a suggested format:

filename: `models.yaml`

```
models:
  - name: Model1
    url: https://example.com/model1.pth
    destination: models/model1.pth
    checksum: abcdef1234567890
  - name: Model2
    url: https://example.com/model2.onnx
    destination: models/model2.onnx
    checksum: 123456abcdef7890
  - name: Model3
    url: https://example.com/model3.h5
    destination: models/model3.h5
    checksum: 7890abcdef123456
```

I think `checksum` should be optional.

Now, here is an example `models.yaml` for the IPAdapter Plus node according to its [README.md](https://github.com/cubiq/ComfyUI_IPAdapter_plus/blob/main/README.md) (They do need a lot of models.)

```
models:
  - name: CLIP-ViT-H-14-laion2B-s32B-b79K
    url: https://huggingface.co/h94/IP-Adapter/resolve/main/models/image_encoder/model.safetensors
    destination: /ComfyUI/models/clip_vision/CLIP-ViT-H-14-laion2B-s32B-b79K.safetensors
  - name: CLIP-ViT-bigG-14-laion2B-39B-b160k
    url: https://huggingface.co/h94/IP-Adapter/resolve/main/sdxl_models/image_encoder/model.safetensors
    destination: /ComfyUI/models/clip_vision/CLIP-ViT-bigG-14-laion2B-39B-b160k.safetensors
  - name: ip-adapter_sd15
    url: https://huggingface.co/h94/IP-Adapter/resolve/main/models/ip-adapter_sd15.safetensors
    destination: /ComfyUI/models/ipadapter/ip-adapter_sd15.safetensors
  - name: ip-adapter_sd15_light_v11
    url: https://huggingface.co/h94/IP-Adapter/resolve/main/models/ip-adapter_sd15_light_v11.bin
    destination: /ComfyUI/models/ipadapter/ip-adapter_sd15_light_v11.bin
  - name: ip-adapter-plus_sd15
    url: https://huggingface.co/h94/IP-Adapter/resolve/main/models/ip-adapter-plus_sd15.safetensors
    destination: /ComfyUI/models/ipadapter/ip-adapter-plus_sd15.safetensors
  - name: ip-adapter-plus-face_sd15
    url: https://huggingface.co/h94/IP-Adapter/resolve/main/models/ip-adapter-plus-face_sd15.safetensors
    destination: /ComfyUI/models/ipadapter/ip-adapter-plus-face_sd15.safetensors
  - name: ip-adapter-full-face_sd15
    url: https://huggingface.co/h94/IP-Adapter/resolve/main/models/ip-adapter-full-face_sd15.safetensors
    destination: /ComfyUI/models/ipadapter/ip-adapter-full-face_sd15.safetensors
  - name: ip-adapter_sd15_vit-G
    url: https://huggingface.co/h94/IP-Adapter/resolve/main/models/ip-adapter_sd15_vit-G.safetensors
    destination: /ComfyUI/models/ipadapter/ip-adapter_sd15_vit-G.safetensors
  - name: ip-adapter_sdxl_vit-h
    url: https://huggingface.co/h94/IP-Adapter/resolve/main/sdxl_models/ip-adapter_sdxl_vit-h.safetensors
    destination: /ComfyUI/models/ipadapter/ip-adapter_sdxl_vit-h.safetensors
  - name: ip-adapter-plus_sdxl_vit-h
    url: https://huggingface.co/h94/IP-Adapter/resolve/main/sdxl_models/ip-adapter-plus_sdxl_vit-h.safetensors
    destination: /ComfyUI/models/ipadapter/ip-adapter-plus_sdxl_vit-h.safetensors
  - name: ip-adapter-plus-face_sdxl_vit-h
    url: https://huggingface.co/h94/IP-Adapter/resolve/main/sdxl_models/ip-adapter-plus-face_sdxl_vit-h.safetensors
    destination: /ComfyUI/models/ipadapter/ip-adapter-plus-face_sdxl_vit-h.safetensors
  - name: ip-adapter_sdxl
    url: https://huggingface.co/h94/IP-Adapter/resolve/main/sdxl_models/ip-adapter_sdxl.safetensors
    destination: /ComfyUI/models/ipadapter/ip-adapter_sdxl.safetensors
  - name: ip-adapter-faceid_sd15
    url: https://huggingface.co/h94/IP-Adapter-FaceID/resolve/main/ip-adapter-faceid_sd15.bin
    destination: /ComfyUI/models/ipadapter/ip-adapter-faceid_sd15.bin
  - name: ip-adapter-faceid-plusv2_sd15
    url: https://huggingface.co/h94/IP-Adapter-FaceID/resolve/main/ip-adapter-faceid-plusv2_sd15.bin
    destination: /ComfyUI/models/ipadapter/ip-adapter-faceid-plusv2_sd15.bin
  - name: ip-adapter-faceid-portrait-v11_sd15
    url: https://huggingface.co/h94/IP-Adapter-FaceID/resolve/main/ip-adapter-faceid-portrait-v11_sd15.bin
    destination: /ComfyUI/models/ipadapter/ip-adapter-faceid-portrait-v11_sd15.bin
  - name: ip-adapter-faceid_sdxl
    url: https://huggingface.co/h94/IP-Adapter-FaceID/resolve/main/ip-adapter-faceid_sdxl.bin
    destination: /ComfyUI/models/ipadapter/ip-adapter-faceid_sdxl.bin
  - name: ip-adapter-faceid-plusv2_sdxl
    url: https://huggingface.co/h94/IP-Adapter-FaceID/resolve/main/ip-adapter-faceid-plusv2_sdxl.bin
    destination: /ComfyUI/models/ipadapter/ip-adapter-faceid-plusv2_sdxl.bin
  - name: ip-adapter-faceid-portrait_sdxl
    url: https://huggingface.co/h94/IP-Adapter-FaceID/resolve/main/ip-adapter-faceid-portrait_sdxl.bin
    destination: /ComfyUI/models/ipadapter/ip-adapter-faceid-portrait_sdxl.bin
  - name: ip-adapter-faceid-portrait_sdxl_unnorm
    url: https://huggingface.co/h94/IP-Adapter-FaceID/resolve/main/ip-adapter-faceid-portrait_sdxl_unnorm.bin
    destination: /ComfyUI/models/ipadapter/ip-adapter-faceid-portrait_sdxl_unnorm.bin
  - name: ip-adapter-faceid_sd15_lora
    url: https://huggingface.co/h94/IP-Adapter-FaceID/resolve/main/ip-adapter-faceid_sd15_lora.safetensors
    destination: /ComfyUI/models/loras/ip-adapter-faceid_sd15_lora.safetensors
  - name: ip-adapter-faceid-plusv2_sd15_lora
    url: https://huggingface.co/h94/IP-Adapter-FaceID/resolve/main/ip-adapter-faceid-plusv2_sd15_lora.safetensors
    destination: /ComfyUI/models/loras/ip-adapter-faceid-plusv2_sd15_lora.safetensors
  - name: ip-adapter-faceid_sdxl_lora
    url: https://huggingface.co/h94/IP-Adapter-FaceID/resolve/main/ip-adapter-faceid_sdxl_lora.safetensors
    destination: /ComfyUI/models/loras/ip-adapter-faceid_sdxl_lora.safetensors
  - name: ip-adapter-faceid-plusv2_sdxl_lora
    url: https://huggingface.co/h94/IP-Adapter-FaceID/resolve/main/ip-adapter-faceid-plusv2_sdxl_lora.safetensors
    destination: /ComfyUI/models/loras/ip-adapter-faceid-plusv2_sdxl_lora.safetensors
  - name: ip_plus_composition_sd15
    url: https://huggingface.co/ostris/ip-composition-adapter/resolve/main/ip_plus_composition_sd15.safetensors
    destination: /ComfyUI/models/ipadapter/ip_plus_composition_sd15.safetensors
  - name: ip_plus_composition_sdxl
    url: https://huggingface.co/ostris/ip-composition-adapter/resolve/main/ip_plus_composition_sdxl.safetensors
    destination: /ComfyUI/models/ipadapter/ip_plus_composition_sdxl.safetensors
```
